auto_test:
  stage: test
  script: ci/auto_test.sh
  except:
    - master
  tags:
    - sonar

sonar_preview:
  stage: test
  script:
    - ci/sonar_preview.sh
  except:
    - master
  tags:
    - sonar

sonar_analyze:
  stage: test
  script:
    - ci/sonar_analyze.sh
  only:
    - master
  tags:
    - sonar
